import 'package:flutter/material.dart';

class AppColors {
  AppColors._();

  static const backgroundLight = Color(0xFFFFFFFF);
  static const backgroundDark = Color(0xFF0F1624);
  static const primary = Color(0xFF4364AF);
  static const secondaryDefault = Color(0xFF3D3D3D);
  static const white = Color(0xFFFFFFFF);
  static const black = Color(0xFF000000);
  static const grey1 = Color(0xFF1E2328);
  static const grey2 = Color(0xFF34383D);
  static const grey3 = Color(0xFF616568);
  static const grey4 = Color(0xFF8E9193);
  static const grey5 = Color(0xFFBBBDBE);
  static const grey6 = Color(0xFFE8E9E9);
  static const neutral01 = Color(0xFF37393D);
  static const neutral02 = Color(0xFF414348);
  static const neutral03 = Color(0xFF737680);
  static const neutral04 = Color(0xFF818590);
  static const neutral05 = Color(0xFFAAAFBD);
  static const neutral06 = Color(0xFFB8BDCC);
  static const neutral07 = Color(0xFFD0D3DA);
  static const neutral08 = Color(0xFFDDDFE4);
  static const neutral09 = Color(0xFFEBECEF);
  static const neutral10 = Color(0xFFF8F8FA);
  static const neutral20 = Color(0xFFF5F5F5);
  static const neutralBlack = Color(0xFF0A0A0A);
  static const borderLight = Color(0xFFEDF2F7);
  static const background = Color(0xFFF4F2F4);
  static const scaffoldBackground = Color(0xFFF5F5F5);
  static const primaryLight900 = Color(0xFFFFFAE7);
  static const greyBackground = Color(0xFFFCFCFC);
  static const surfacePrimary = Color(0xFFF7F8FD);
  static const primaryLight = Color(0xFFFFF5D0);
  static const informationSoft = Color(0xFFE5EDFE);
  static const information = Color(0xFF5487F5);
  static const alertSoft = Color(0xFFFFF4D9);
  static const alertDefault = Color(0xFFDEAD00);
  static const successSoft = Color(0xFFD5F2EA);
  static const successDefault = Color(0xFF00C48C);
  static const errorSoft = Color(0xFFFFE1E1);
  static const errorDefault = Color(0xFFD53A3A);
  static const warningSoft = Color(0xFFFFF1E9);
  static const warningDefault = Color(0xFFFF802C);
  static const pendingSoft = Color(0xFFF4E7FF);
  static const pendingDefault = Color(0xFF9624F0);
  static const heartDefault = Color(0xFFE16486);
}
